### ISSUE TITLE
Q: log to string?

### ISSUE THREAD

**Issue by jrochkind** [rudionrails/yell#39]
For testing purposes, it would be convenient if I could temporarily set something to use a logger that simply writes to a String or StringIO object, so I can check what was logged in my tests. Instead of to a file. Or to the standard stdout/stderr. 

Is this possible with Yell, can I create a logger that writes to a StringIO or String instead of to a file?

**Comment by rudionrails** [comment]
Yes sure. You can either read the tests for yell in order to see how it is done there, or you can write your own adapter for it. Like so:

```ruby
require 'yell'

# out write stream
require 'stringio'
$stringio = StringIO.new

# our new adapter that only assigns the global variable to the @stream
class StringAdapter < Yell::Adapters::Io
  open { @stream = $stringio }
end

# do the logging stuff
logger = Yell.new(StringAdapter.new)

Yell::Severities.each do |level|
  logger.send level.downcase, level
end

# inspect your string
puts $stringio.string
```

You only need to take care to rewind the `$stringio` after every test. Hope that helps.

**Comment by jrochkind** [comment]
thanks!
