### ISSUE TITLE
Undefined method env for Rails module

### ISSUE THREAD

**Issue by smackesey** [rudionrails/yell#40]
I recently updated my bundle and now am encountering this error when doing Yell.new(/some/path):

>/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yell-2.0.5/lib/yell.rb:86:in `env': undefined method `env' for Rails:Module (NoMethodError)

**Comment by rudionrails** [comment]
Can you post the full stack-trace please. Also, which version of Rails are you running?

**Comment by smackesey** [comment]
This was months ago, so I can't remember the context. I did just try running the command again and it worked this time though. Also, I was not running Rails at all.

**Comment by rudionrails** [comment]
Yea, sorry for the delay in response. Your code snipped suggested that `Rails` module is defined :) Closing the issue now.
