### ISSUE TITLE
Tests fail on a recent rebuild in Debian

### ISSUE THREAD

**Issue by mr-c** [rudionrails/yell#43]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841576

While I am the packager, I don't know enough ruby to diagnose this, so assistance is appreciated.

**Comment by rudionrails** [comment]
Hey there, the stack-trace is missing some information to fully reproduce the errors. I've released yell-2.0.7. Can you please give it a try and get back to me.

**Comment by mr-c** [comment]
@rudionrails Looks like 2.0.7 [built and the test ran successfully](https://buildd.debian.org/status/fetch.php?pkg=ruby-yell&arch=all&ver=2.0.7-1&stamp=1477391250) -- thanks for the new release!
