### ISSUE TITLE
Refactor symbol hashes to >1.9 hash syntax

### ISSUE THREAD

**Issue by IotaSpencer** [rudionrails/yell#52]
Was reading through some of the source code and noticed in some of the doc comments and code, that you're using <1.9 hash syntax, would it be ok if I were to submit a pull request to fix that?

**Comment by rudionrails** [comment]
@IotaSpencer go for it. 1.9 support was kept due to JRuby compatibility. Looking forward to the PR

**Comment by IotaSpencer** [comment]
do you care for jruby or is that fixed nowadays

**Comment by IotaSpencer** [comment]
PR #53 Ready for review and merge
